sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: test
    password: test
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tMCpGwg41BwLkMFifAZ
    access-key-secret: dLRdvqygMXu4qbtHU9850Tmcgges9B
    bucket-name: davidaed-files
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  wechat:
    appid: wx6158b822e736be42
    secret: 75dc3bffaa0a1610c6ed3545b854fda6